import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'appName': 'Event',
      'home': 'Home',
      'eventCalender': 'Event Calender',
      'Calender': 'Calender',
      'selectlaunguage': 'Select Language',
      'Submit': 'Submit',
      //---- bottom screen ----
      'Explore':'Explore',
      'Videos':'Videos',
      'Profile':'Profile',
      //---- home screen ---
      "Vance Corwin":"Vance Corwin",
      "20 min ago":"20 min ago",
      "Christina Perri":"Christina Perri",
      "30 min ago":"30 min ago",
      "Ewa Farna":"Ewa Farna",
      "40 min ago":"40 min ago",
      "Follow":"Follow",
      'Unfollow':"Unfollow",
      'Hide':'Hide',
      'Report ':'Report ',
      //----- comment screen -----
      'Comments':'Comments',
      '56':'56',
      'Emiway Berkle':'Emiway Berkle',
      '3 hrs ago':'3 hrs ago',
      "Your Event is so superb.i’m so enjoy this event shows.":"Your Event is so superb.i’m so enjoy this event shows.",
      'Franciso Gibbs':'Franciso Gibbs',
      '4 hrs ago':'4 hrs ago',
      "Lorem ipsum dolor sit amet consectetur.Gravida feugiat commodo .":"Lorem ipsum dolor sit amet consectetur.Gravida feugiat commodo .",
      'Anya':'Anya',
      'Liza Scott':'Liza Scott',
      'Tamunal12':'Tamunal12',
      'Henry Harvey':'Henry Harvey',
      'George':'George',
      "Yes i agree with your opnion...":"Yes i agree with your opnion...",
      'Nick':'Nick',
      'Add A Comment':'Add A Comment',
      'Linked':'Linked',
      'Reply':'Reply',
      //------ detail page screen ----
      'Christina Perri Live In Concert':'Christina Perri Live In Concert',
      "Hollywood":"Hollywood",
      "Hindi":"Hindi",
      "2hrs 30mins":"2hrs 30mins",
      "\$999":"\$999",
      "onwords":"onwords",
      "Sat Jun 29,6pm-9pm":"Sat Jun 29,6pm-9pm",
      "4746 MacLaren Stree, Ottawa, Ontario Canada-K1P 5M7":"4746 MacLaren Stree, Ottawa, Ontario Canada-K1P 5M7",
      "+ Join":"+ Join",
      "320+ interested":"320+ interested",
      "4.8":"4.8",
      "320+ reviews":"320+ reviews",
      "About":"About",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi, viverra crasvarss us. "
          "Nec vitae ac sit tristique.Lectus in augue aliquam neque luctus nun "
          ",duis urna tellus. Sit lorem magna sit nisi, viverra crasvar us. Nec vi "
          "tae ac sit tristique gas dhjkd augue sit nisi elit magna.":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi, viverra crasvarss us. "
          "Nec vitae ac sit tristique.Lectus in augue aliquam neque luctus nun "
          ",duis urna tellus. Sit lorem magna sit nisi, viverra crasvar us. Nec vi "
          "tae ac sit tristique gas dhjkd augue sit nisi elit magna.",
      "Artists":"Artists",
      'Playback singer':'Playback singer',
      'Contacts':'Contacts',
      "Casandra Johnstone":"Casandra Johnstone",
      "Event Organizer":"Event Organizer",
      "+91 12345 67890":"+91 12345 67890",
      "Terms & Conditions":"Terms & Conditions",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi.":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi.",
      "Invite":"Invite",
      "Get Tickets":"Get Tickets",
      //---- ticket tyype screen ---
      'Ticket type':'Ticket type',
      "Silver":"Silver",
      "\$ 100":"\$ 100",
      "Gold":"Gold",
      "\$ 250":"\$ 250",
      "Platinum":"Platinum",
      "\$ 300":"\$ 300",
      "Quantity":"Quantity",
      "Total Price":"Total Price",
      "Proceed to pay":"Proceed to pay",
      //---- payment method screen -----
      'Saved cards':'Saved cards',
      'Add Card':'Add Card',
          'EXPIRY DATE':'EXPIRY DATE',
      'CARD HOLDER NAME':'CARD HOLDER NAME',
      'Other Ways to Pay':'Other Ways to Pay',
      'Google Pay':'Google Pay',
      'Apple Pay':'Apple Pay',
      'Paypal':'Paypal',
      'Amount to Pay: ':'Amount to Pay: ',
      //---- add acrd screen ---
      'Number':'Number',
      'Expired Date':'Expired Date',
      'CVV':'CVV',
      'Card Holder':'Card Holder',
      //---- ticket payment successful screen---
      "Tickets Purchased Successfully":"Tickets Purchased Successfully",
      "Transaction ID":"Transaction ID",
      "EVNT4783929":"EVNT4783929",
      "Total Paid":"Total Paid",
      "Tickets":"Tickets",
      "Silver Tickets":"Silver Tickets",
      "Event Details":"Event Details",
      "Christina Perri Live In Concert ":"Christina Perri Live In Concert ",
      "31 December, Sunday":"31 December, Sunday",
      "Ottawa, Canada":"Ottawa, Canada",
      "6pm-9pm":"6pm-9pm",
      "View Tickets":"View Tickets",
      "Done":"Done",
      //--- view tickets screen ---
      "Ticket Status":"Ticket Status",
      "Not used":"Not used",
      "Back to Home":"Back to Home",
      //--- calender screen---
      "Sun":"Sun",
      "Mon":"Mon",
      "Tue":"Tue",
      "Wed":"Wed",
      "Thu":"Thu",
      "Fri":"Fri",
      "Sat":"Sat",
      "Jan":"Jan",
      "Feb":"Feb",
      "March":"March",
      "April":"April",
      "May":"May",
      "June":"June",
      "July":"July",
      "Aug":"Aug",
      "Sep":"Sep",
      "Oct":"Oct",
      "Nov":"Nov",
      "Dec":"Dec",
      'Events for you':'Events for you',
      'Stand Up Comedy':'Stand Up Comedy',
      'Your Events':'Your Events',
      'Singing Event':'Singing Event',
      'Follower’s Events':'Follower’s Events',
      'Dancing':'Dancing',
      "January":"January",
      "February":"February",
      "August":"August",
      "September":"September",
      "October":"October",
      "November":"November",
      "December":"December",
      '15 Jun, 2022':'15 Jun, 2022',
      'Surat':'Surat',
      '+ Interested':'+ Interested',
//----- event for you screen --------
      'Car exhibition':'Car exhibition',
      'Music Party':'Music Party',
      'Christina Perri Live In Concert':'Christina Perri Live In Concert',
      'Upcoming':'Upcoming',
      'Past':'Past',
      '20,Dec 2022':'20,Dec 2022',
//----- explore screen -------
'Car Expo':'Car Expo',
      "15 Jun,2022":"15 Jun,2022",
      "Free":"Free",
      "300":"300",
      "Conference":"Conference",
      "20 Jun,2022":"20 Jun,2022",
      "Fashion Show":"Fashion Show",
      "25 Jun,2022":"25 Jun,2022",
      "200":"200",
      "Concert":"Concert",
      "27 Jun,2022":"27 Jun,2022",
      "Bike Expo":"Bike Expo",
      "30 Jun,2022":"30 Jun,2022",

      "Workshop":"Workshop",
      'Categories':'Categories',
      "Parties":"Parties",
      "Social meets":"Social meets",
      "Exhibition":"Exhibition",
      "Celebration":"Celebration",
      "Performance":"Performance",
      "Fun & Game":"Fun & Game",
      "Concerts":"Concerts",
      'Nearby':'Nearby',
      "Business conference":"Business conference",
      "Los Angeles":"Los Angeles",
      "Cirque Musica Querida":"Cirque Musica Querida",
      "20 Jun, 2022":"20 Jun, 2022",
      "Mexico":"Mexico",
      "Sweet Baby James":"Sweet Baby James",
      "22 Jun, 2022":"22 Jun, 2022",
      "New York":"New York",
      "Art with Me Miami":"Art with Me Miami",
      "25 Jun, 2022":"25 Jun, 2022",
      "Bangkok":"Bangkok",
      "28 Jun, 2022":"28 Jun, 2022",
      "+ interested":"+ interested",
      "K":"K",
      //------ videos screen -----
      'Alex Gorje':'Alex Gorje',
      'Goargia Wilson':'Goargia Wilson',
      'Pokemon World':'Pokemon World',
      'Holi Day':'Holi Day',
      'Wonder Night':'Wonder Night',
      'Highlights':'Highlights',
//----- profile screen-----

      "Ux/Ui designer":"Ux/Ui designer",
      "Edit profile":"Edit profile",
      "Posts":"Posts",
      "Followers":"Followers",
      "Following":"Following",
      'Stories':'Stories',

//---- MessageScreen ----
      'Lizza_Scott':'Lizza_Scott',
      'Search':'Search',
      "Messages":"Messages",
      '03:26AM':'03:26AM',
      '12:26PM':'12:26PM',
      '26:06PM':'26:06PM',
      '01:23PM':'01:23PM',
      '11:20PM':'11:20PM',
      '05:45AM':'05:45AM',


      //----- message detail screen----
      "Today":"Today",
      "Yesterday":"Yesterday",
      " Selected":" Selected",
      'Type a message':'Type a message',
      '13:12PM':'13:12PM',
      "Hello,I want to plan event for my Birthday so can you send your details.":"Hello,I want to plan event for my Birthday so can you send your details.",
      '13:24PM':'13:24PM',
      "Yes,Sure i will send":"Yes,Sure i will send",
      '13:25PM':'13:25PM',
      "Which date your Birthday?":"Which date your Birthday?",
      '10:06PM':'10:06PM',
      "23/02 it’s my Birthdate":"23/02 it’s my Birthdate",
      '10:07PM':'10:07PM',
      "Ok,I will confirmed your date.":"Ok,I will confirmed your date.",
      //----- edit profile screen ---
      'Edit Profile':'Edit Profile',
      'Change Profile Photo':'Change Profile Photo',
      'Name':'Name',
      'Enter your name':'Enter your name',
      'E-mail':'E-mail',
      'Enter your email':'Enter your email',
      'Birthdate':'Birthdate',
      'Enter your birthdate':'Enter your birthdate',
      "dd-MMMM-yyyy":"dd-MMMM-yyyy",
      'Phone':'Phone',
      'Enter your phonenumber':'Enter your phonenumber',
      'Bio':'Bio',
      'Enter your bio':'Enter your bio',
      //-- validation ----
      'Please enter your name':'Please enter your name',
      'Please enter your email':'Please enter your email',
      'Please enter your birthdate':'Please enter your birthdate',
      'Please enter your phonenumber': 'Please enter your phonenumber',
      'Please enter your bio':'Please enter your bio',

      //--- onboarding screen ---
      "Discover Events":"Discover Events",
      "Explore all type of events and easy event booking":"Explore all type of events and easy event booking",
      "Share your Event":"Share your Event",
      "Share you event experience via post and stories":"Share you event experience via post and stories",
      "Make a Network":"Make a Network",
      "Expand your network & stay connect with your event mates":"Expand your network & stay connect with your event mates",
      "Create Event":"Create Event",
  "Easily make the event and published your events":"Easily make the event and published your events",
      "Get started":"Get started",
      //--- login screen ---
      "Welcome back!":"Welcome back!",
      'Please enter your name or email':'Please enter your name or email',
      'Email/Mobile no': 'Email/Mobile no',
      'Please enter your password':'Please enter your password',
      'Password':'Password',
      "Remember me":"Remember me",
      "Forgot Password?":"Forgot Password?",
      "Log In":"Log In",
      "Sign up":"Sign up",
      //--- signup screen ----
      "Let’s \nGet Started!":"Let’s \nGet Started!",
      'User name':'User name',
      'Please enter your email or phonenumber':'Please enter your email or phonenumber',
      'Please enter your  confirm password':'Please enter your  confirm password',
      'Confirm Password':'Confirm Password',
      //---- video details screen ---
      ' video upload':' video upload',
      //---- category screen ----
      'Choose Categories that represent what you want to see ':'Choose Categories that represent what you want to see ',
      "Continue":"Continue",
      "Business":"Business",
      "Sports":"Sports",
      "Education":"Education",
      "Fitness":"Fitness",
      "Health":"Health",
      "Food":"Food",
      "Travel":"Travel",
      "Retail":"Retail",
      "Music":"Music",
      //--- logout --
      "Log Out":"LogOut",
      'Are You sure you want to logout?':'Are You sure you want to logout?',
      'Yes':'Yes',
      'No':'No',

    },
    'hi_IN': {
      'appName': 'आयोजन',
      'home': 'घर',
    },
    'gu_IN': {
      'appName': 'ઘટના',
      'home': 'ઘર',
    },
    'ar_AE': {
      'selectlaunguage': 'اختار اللغة',
      'Submit': 'يقدم',
      'home': 'مسكن',
      //---- bottom screen ----
      'Explore':'يكتشف',
      'Videos':'أشرطة فيديو',
      'Profile':'الملف الشخصي',
      'Calender': 'تقويم',
      //---- home screen ---
      "Vance Corwin":"فانس كوروين",
      "20 min ago":"قبل 20 دقيقة",
      "Christina Perri":"كريستينا بيري",
      "30 min ago":"قبل 30 دقيقة",
      "Ewa Farna":"إيوا فرنا",
      "40 min ago":"قبل 40 دقيقة",
      "Follow":'يتبع',
      'Unfollow':"الغاء المتابعة",
      'Hide':'يخفي',
      'Report ':'تقرير',
      //---- comment screen -----
      'Comments':'تعليقات',
      '56':'ستة وخمسون',
      'Emiway Berkle':'إميواي بيركل',
      '3 hrs ago':'قبل 3 ساعات',
      "Your Event is so superb.i’m so enjoy this event shows.":"إن حدثك رائع للغاية ، لذا فأنا استمتع بعروض هذا الحدث.",
      'Franciso Gibbs':'فرانسيسكو جيبس',
      '4 hrs ago':'قبل 4 ساعات',
      "Lorem ipsum dolor sit amet consectetur.Gravida feugiat commodo .":"Lorem ipsum dolor sit amet consectetur.Gravida feugiat commodo .",
      'Anya':'أنيا',
      'Liza Scott':'ليزا سكوت',
      'Tamunal12':'تامونال 12',
      'Henry Harvey':'هنري هارفي',
      'George':'جورج',
      'Vance Corwin':'فانس كوروين',
      "Yes i agree with your opnion...":"نعم أوافق على رأيك ...",
      'Nick':'نيك',
      'Add A Comment':'اضف تعليق',
      'Linked':'ينكدين',
      'Reply':'رد',
      //------ detail page screen ----
      'Christina Perri Live In Concert':'كريستينا بيري تعيش في حفلة موسيقية',
      "Hollywood":"هوليوود",
      "Hindi":"هندي",
      "2hrs 30mins":"ساعتان و 30 دقيقة",
      "\$999":"999 دولار",
      "onwords":"على كلمات",
      "Sat Jun 29,6pm-9pm":"السبت 29 يونيو ، 6 مساءً - 9 مساءً",
      "4746 MacLaren Stree, Ottawa, Ontario Canada-K1P 5M7":"",
      "+ Join":"+ انضمام",
      "320+ interested":"320+ مهتم",
      "4.8":"4.8",
      "320+ reviews":"320+ آراء",
      "About":"حول",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi, viverra crasvarss us. "
          "Nec vitae ac sit tristique.Lectus in augue aliquam neque luctus nun "
          ",duis urna tellus. Sit lorem magna sit nisi, viverra crasvar us. Nec vi "
          "tae ac sit tristique gas dhjkd augue sit nisi elit magna.":"يشير النص الوهمي إلى أجزاء المحتوى المستخدمة لملء نموذج موقع الويب. يساعد هذا النص مصممي الويب على تصور أفضل لكيفية ظهور موقع الويب كمنتج نهائي. من المهم أن نفهم أن النص الوهمي ليس له معنى على الإطلاق. والغرض الوحيد منه هو ملء الفراغات بمحتوى ",
      "Artists":"الفنانين",
      'Playback singer':'تشغيل المغني',
      'Contacts':'جهات الاتصال',
      "Casandra Johnstone":"كاساندرا جونستون",
      "Event Organizer":"منظم الحدث",
      "+91 12345 67890":"+91 12345 67890",
      "Terms & Conditions":"البنود و الظروف",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accum "
          "san etiam diam nunc proin. Sit lorem magna sit nisi, viverra crasvar "
          "us. Nec vitae ac sit tristique. Lectus in augue aliquam neque luctus "
          "nunc, duis urna tellus. Sit lorem magna sit nisi.":"يشير النص الوهمي إلى أجزاء المحتوى المستخدمة لملء نموذج موقع الويب. يساعد هذا النص مصممي الويب على تصور أفضل لكيفية ظهور موقع الويب كمنتج نهائي. من المهم أن نفهم أن النص الوهمي ليس له معنى على الإطلاق. والغرض الوحيد منه هو ملء الفراغات بمحتوى "" ، دون القيام بأي انتهاك لحقوق النشر.",
      "Invite":"يدعو",
      "Get Tickets":"أحصل على تذاكر",
      //---- ticket tyype screen ---
      'Ticket type':'نوع التذكرة',
      "Silver":"فضة",
      "\$ 100":"\$ 100 دولار",
      "Gold":"ذهب",
      "\$ 250":"250 دولار",
      "Platinum":"البلاتين",
      "\$ 300":"300 دولار",
      "Quantity":"كمية",
      "Total Price":"السعر الكلي",
      "Proceed to pay":"المضي قدما في الدفع",
      //---- payment method screen -----
      'Saved cards':'البطاقات المحفوظة',
      'Add Card':'إضافة بطاقة',
      'EXPIRY DATE':'تاريخ انتهاء الصلاحية',
      'CARD HOLDER NAME':'إسم صاحب البطاقة',
      'Other Ways to Pay':'طرق أخرى للدفع',
      'Google Pay':'جوجل باي',
      'Apple Pay':'Apple Pay',
      'Paypal':'باي بال',
      'Amount to Pay: ':'مبلغ الدفع:',
      //---- add acrd screen ---
      'Number':'رقم',
      'Expired Date':'منتهي الصلاحية',
      'CVV':'CVV',
      'Card Holder':'حامل البطاقة',
      //---- ticket payment successful screen---
      "Tickets Purchased Successfully":"تم شراء التذاكر بنجاح",
      "Transaction ID":"رقم المعاملة",
      "EVNT4783929":"EVNT4783929",
      "Total Paid":"مجموع المبالغ المدفوعة",
      "Tickets":"تذاكر",
      "Silver Tickets":"التذاكر الفضية",
      "Event Details":"تفاصيل الحدث",
      "Christina Perri Live In Concert ":"كريستينا بيري تعيش في حفلة موسيقية",
      "31 December, Sunday":"31 ديسمبر ، الأحد",
      "Ottawa, Canada":"أوتاوا ، كندا",
      "6pm-9pm":"6 مساءً - 9 مساءً",
      "View Tickets":"عرض التذاكر",
      "Done":"فعله",
//--- view tickets screen ---
      "Ticket Status":"حالة التذكرة",
      "Not used":"غير مستعمل",
      "Back to Home":"العودة إلى المنزل",
      //--- calender screen---
      'eventCalender':'تقويم الحدث',
      "Sun":"شمس",
      "Mon":"الإثنين",
      "Tue":"الثلاثاء",
      "Wed":"تزوج",
      "Thu":"خميس",
      "Fri":"الجمعة",
      "Sat":"جلس",
      "Jan":"يناير",
      "Feb":"فبراير",
      "March":"يمشي",
      "April":"أبريل",
      "May":"مايو",
      "June":"يونيه",
      "July":"يوليو",
      "Aug":"أغسطس",
      "Sep":"سبتمبر",
      "Oct":"أكتوبر",
      "Nov":"نوفمبر",
      "Dec":"ديسمبر",
      'Events for you':'أحداث لك',
      'Stand Up Comedy':'كوميديا ​​الوقوف',
      'Your Events':'الأحداث الخاصة بك',
      'Singing Event':'حدث الغناء',
      'Follower’s Events':'أحداث التابعين',
      'Dancing':'الرقص',
      "January":"يناير",
      "February":"شهر فبراير",
      "August":"أغسطس",
      "September":"سبتمبر",
      "October":"اكتوبر",
      "November":"شهر نوفمبر",
      "December":"ديسمبر",
      '15 Jun, 2022':'15 يونيو 2022',
      'Surat':'سورة',
      '+ Interested':'+ مهتم',
//----- event for you screen --------
      'Car exhibition':'معرض سيارات',
      'Music Party':'حفلة موسيقية',
      'Christina Perri Live In Concert':'كريستينا بيري تعيش في حفلة موسيقية',
      'Upcoming':'القادمة',
      'Past':'ماضي',
      '20,Dec 2022':'20 ، ديسمبر 2022',
      //----- explore screen -------
      'Car Expo':'معرض السيارات',
      "15 Jun,2022":"15 يونيو 2022",
      "Free":"حر",
      "300":"300",
      "Conference":"مؤتمر",
      "20 Jun,2022":"20 يونيو 2022",
      "Fashion Show":"عرض ازياء",
      "25 Jun,2022":"25 يونيو 2022",
      "200":"200",
      "Concert":"حفلة موسيقية",
      "27 Jun,2022":"27 يونيو 2022",
      "Bike Expo":"معرض الدراجة",
      "30 Jun,2022":"30 يونيو 2022",


      "Workshop":"ورشة عمل",
      'Categories':'فئات',
      "Parties":"حفلات",
      "Social meets":"اللقاءات الاجتماعية",
      "Exhibition":"معرض",
      "Celebration":"احتفال",
      "Performance":"أداء",
      "Fun & Game":"لعبة ممتعة",
      "Concerts":"حفلات",
      'Nearby':'مجاور',
      "Business conference":"مؤتمر عمل",
      "Los Angeles":"لوس أنجلوس",
      "Cirque Musica Querida":"سيرك ميوزيكا كويريدا",
      "20 Jun, 2022":"20 يونيو 2022",
      "Mexico":"المكسيك",
      "Sweet Baby James":"سويت بيبي جيمس",
      "22 Jun, 2022":"22 يونيو 2022",
      "New York":"نيويورك",
      "Art with Me Miami":"الفن معي ميامي",
      "25 Jun, 2022":"25 يونيو 2022",
      "Bangkok":"بانكوك",
      "28 Jun, 2022":"28 يونيو 2022",
      "+ interested":"+ مهتم",
      "K":"ك",

  //------ videos screen -----
  'Alex Gorje':'أليكس جورجي',
  'Goargia Wilson':'جورجيا ويلسون',
  'Pokemon World':'بوكيمون وورلد',
  'Holi Day':'يوم الاجازة',
  'Wonder Night':'ليلة رائعة',
  'Highlights':'يسلط الضوء',

      //----- profile screen-----

      "Ux/Ui designer":"مصمم Ux / Ui",
      "Edit profile":"تعديل الملف الشخصي",
      "Posts":"المشاركات",
      "Followers":"متابعون",
      "Following":"التالية",
      'Stories':'القصص',
//--- messgae screen---
      'Lizza_Scott':'ليزا سكوت',
      'Search':'يبحث',
      "Messages":"رسائل",
      '03:26AM':'03:26 صباحًا',
      '12:26PM':'12:26 مساءً',
      '26:06PM':'26:06 م',
      '01:23PM':'01:23 مساءً',
      '11:20PM':'11:20 مساءً',
      '05:45AM':'05:45 صباحا',


      //----- message detail screen----
      "Today":"اليوم",
      "Yesterday":"في الامس",
      " Selected":"المحدد",
      'Type a message':'اكتب رسالة',
      '13:12PM':'13:12 م',
      "Hello,I want to plan event for my Birthday so can you send your details.":"مرحبًا ، أريد التخطيط لحدث في عيد ميلادي ، لذا يمكنك إرسال التفاصيل الخاصة بك.",
      '13:24PM':'13:24 مساءً',
      "Yes,Sure i will send":"نعم ، بالتأكيد سأرسل",
      '13:25PM':'13:25 مساءً',
      "Which date your Birthday?":"في أي تاريخ عيد ميلادك؟",
      '10:06PM':'10:06 مساءً',
      "23/02 it’s my Birthdate":"23/02 إنه تاريخ ميلادي",
      '10:07PM':'10:07 م',
      "Ok,I will confirmed your date.":"حسنًا ، سأؤكد تاريخك.",

      //----- edit profile screen ---
      'Edit Profile':'تعديل الملف الشخصي',
      'Change Profile Photo':'تغيير صورة الملف الشخصي',
      'Name':'اسم',
      'Enter your name':'أدخل أسمك',
      'E-mail':'البريد الإلكتروني',
      'Enter your email':'أدخل بريدك الإلكتروني',
      'Birthdate':'تاريخ الميلاد',
      'Enter your birthdate':'أدخل تاريخ ميلادك',
      "dd-MMMM-yyyy":"dd-MMMM-yyyy",
      'Phone':'هاتف',
      'Enter your phonenumber':'أدخل رقم هاتفك',
      'Bio':'السيرة الذاتية',
      'Enter your bio':'أدخل سيرتك الذاتية',

      //-- validation ----
      'Please enter your name':'من فضلك أدخل إسمك',
      'Please enter your email':'رجاءا أدخل بريدك الإلكتروني',
      'Please enter your birthdate':'الرجاء ادخال تاريخ ميلادك',
      'Please enter your phonenumber': 'يرجى إدخال رقم الهاتف الخاص بك',
      'Please enter your bio':'الرجاء إدخال السيرة الذاتية الخاصة بك',

      //--- onboarding screen ---
      "Discover Events":"اكتشف الأحداث",
      "Explore all type of events and easy event booking":"استكشف كل أنواع الأحداث وحجزها بسهولة",
      "Share your Event":"شارك الحدث الخاص بك",
      "Share you event experience via post and stories":"شارك تجربة الحدث لك عبر المنشورات والقصص",
      "Make a Network":"أنشئ شبكة",
      "Expand your network & stay connect with your event mates":"قم بتوسيع شبكتك وابق على اتصال مع زملائك في الحدث",
      "Create Event":"انشاء حدث",
      "Easily make the event and published your events":"بسهولة جعل الحدث ونشر الأحداث الخاصة بك",
      "Get started":"البدء",

      //--- login screen ---
      "Welcome back!":"مرحبًا بعودتك!",
      'Please enter your name or email':'الرجاء إدخال اسمك أو بريدك الإلكتروني',
      'Email/Mobile no': 'البريد الإلكتروني / رقم الجوال',
      'Please enter your password':'من فضلك أدخل رقمك السري',
      'Password':'كلمة المرور',
      "Remember me":"تذكرنى",
      "Forgot Password?":"هل نسيت كلمة السر؟",
      "Log In":"تسجيل الدخول",
      "Sign up":"اشتراك",
      //--- signup screen ----
      "Let’s \nGet Started!":"فلنبدأ \ n نبدأ!",
      'User name':'اسم المستخدم',
      'Please enter your email or phonenumber':'الرجاء إدخال بريدك الإلكتروني أو رقم الهاتف',
      'Please enter your  confirm password':'الرجاء إدخال تأكيد كلمة المرور الخاصة بك',
      'Confirm Password':'تأكيد كلمة المرور',

      //---- video details screen ---
      ' video upload':'تحميل الفيديو',

      //---- category screen ----
      'Choose Categories that represent what you want to see ':'اختر الفئات التي تمثل ما تريد رؤيته',
      "Continue":"يكمل",
      "Business":"اعمال",
      "Sports":"رياضات",
      "Education":"تعليم",
      "Fitness":"اللياقه البدنيه",
      "Health":"صحة",
      "Food":"غذاء",
      "Travel":"يسافر",
      "Retail":"بيع بالتجزئة",
      "Music":"موسيقى",

      //--- logout --
      "Log Out":"تسجيل خروج",
      'Are You sure you want to logout?':'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'Yes':'نعم',
      'No':'رقم',
    },
  };
}
